--- #YAML:1.0
name: CGI-Application-Plugin-HTCompiled
version: 1.01
author:
  - Mark Stosberg<mark@summersault.com>
abstract: Integrate with HTML::Template::Compiled
license: perl
requires:
  CGI::Application: '>= 4.00'
  HTML::Template::Compiled: 0
  Test::Exception: 0
  Test::More: 0
provides:
  CGI::Application::Plugin::HTCompiled:
    file: lib/CGI/Application/Plugin/HTCompiled.pm
    version: 1.01
generated_by: Module::Build version 0.2611
